### ISSUE TITLE
Published NPM module doesn't contain SASS/SCSS.

### ISSUE THREAD

**Issue by MrJoy** [apnsngr/bulma-popover#1]
The published module only contains the compiled CSS (minified and raw), and source map.  The SASS/SCSS modules are omitted, making it impossible to adjust the variables identified in the README.

**Comment by apnsngr** [comment]
Hey! Thanks so much for your feedback!

I must have forgotten to update the extension in `package.json`. I have published a new version (1.0.1) that is properly packaged.

**Comment by MrJoy** [comment]
Wonderful, thank you so much!  And thanks for a very handy, simple, and elegant tool!
