### ISSUE TITLE
Add trigger mode

### ISSUE THREAD

**Issue by mebibou** [apnsngr/bulma-popover#4]
Currently, it is not possible to use this with a completely manual trigger as the default "hover > show popover" is always on.

It would be nice to have options like:
```
.is-popover-hover
.is-popover-manual
```

**Comment by apnsngr** [comment]
Could `is-popover-active` cover this use case or do you need to completely disable triggering the popover on hover?

**Comment by mebibou** [comment]
@apnsngr the idea is to do it similar to tooltips, they could be displayed when you hover the tooltip, or need manual trigger

In this case, since this is all css based, the best would be to have a class to say it is displayed on `hover` and another one to show the popover, so yeah `is-popover-active` would do the trick for the manual trigger I presume

**Comment by apnsngr** [comment]
I would like to keep this CSS only like Bulma is. Let me think on it some more to see if there is a way to do what you would like in a backward compatible way.

**Comment by apnsngr** [comment]
Ok I added the option to disable the hover trigger for the popover using the `is-not-popover-hover` class. An example of using it can be found in the [test page](https://github.com/apnsngr/bulma-popover/blob/7c5494a5befc4f5b33ee168ac39b31a99adda4f6/test/index.html#L111-L134). This feature has been released in the latest 1.1.0 beta.

**Comment by apnsngr** [comment]
This update has been published in version 1.1.0.
